export const USER_ACTION_START = "USER_ACTION_START";
export const USER_ACTION_ERROR = "USER_ACTION_ERROR";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_ADD_SUCCESS = "USER_ADD_SUCCESS";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
